<?php /* @var $block Fidesio\Donation\Block\Donation\DonationBlock */  ?>

    <section class="fidesio-donation">
        <header>
            <h3>
                <?php echo __('Support a charity with your donation'); ?>
            </h3>
        </header>
        <p>
            <?php echo __('Pick one of our favorite charities and donate'); ?>
        </p>
        <section class="fidesio-donation-product-list">
            <header>
                <h4><?php echo __('Charities that can use your support'); ?></h4>
                <p class="fidesio-donation-mobile-instructions">
                    <?php echo __('Click a Charity to support'); ?>
                </p>
            </header>

                <article
                      <a title="" class="fidesio-donation-image-wrapper">
                        <img src="" alt="" class="fidesio-donation-product-image" />
                    </a>
                    <a class="fidesio-donation-product-tocart">
                        <?php echo __('I want to donate'); ?>
                    </a>
                </article>

        </section>
    </section>

    <div class="fidesio-donation-modal">
        <article>
            <img src="" alt="" class="charity-image" />
            <p class="charity-description"></p>
        </article>
        <form method="POST" class="charity-form" id="fidesio-donation-product-addtocart-form-<?php echo $block->getIdentifier(); ?>">
            <?php echo $block->getBlockHtml('formkey'); ?>
            <div class="fidesio-donation-amounts" data-role="">
                <div class="fidesio-donation-fixed-amounts">
                    <?php foreach ($block->getFixedAmounts() as $fixedAmount => $viewFixedAmount) : ?>
                        <input type="radio" name="amount_fixed" class="input-radio-amount-<?php echo $block->getIdentifier(); ?>" id="amount-fixed-<?php echo $fixedAmount; ?>-<?php echo $block->getIdentifier(); ?>" value="<?php echo $fixedAmount; ?>">
                        <label for="amount-fixed-<?php echo $fixedAmount; ?>-<?php echo $block->getIdentifier(); ?>" class="fidesio-donation-amount-label" data-amount="<?php echo $fixedAmount; ?>">
                            <span><?php echo $viewFixedAmount; ?></span>
                        </label>
                    <?php endforeach; ?>
                </div>
                <label class="label">
                    <span class="fidesio-donation-minimal-amount-label-<?php echo $block->getIdentifier(); ?>"><?php echo __('Choose your own Amount %1 (minimum %2)', $block->getCurrencySymbol()); ?></span>
                </label>
                <p class="fidesio-donation-custom-amount">
                    <span class="custom-donation-amount-field">
                        <span class="custom-amount-currency-symbol"><?php echo $block->getCurrencySymbol(); ?></span>
                        <input id="custom-amount-input-<?php echo $block->getIdentifier(); ?>" name="amount" title="amount" class="input-text validate-number" type="text" value="">
                    </span>
                </p>
                <p class="fidesio-donation-amount-notification">
                    <?php echo __('The selected amount will be added to your shopping cart.'); ?>
                </p>
            </div>
            <div class="fidesio-donation-form-actions">
                <button type="submit" class="button charity-button action primary"><?php echo __('I want to donate this amount'); ?></button>
            </div>
        </form>
    </div>

    <script type="text/x-magento-init">
    {
        "*": {
            "donation":
            {
                "popupContainer":".fidesio-donation-modal",
                "identifier": "<?php echo $block->getIdentifier(); ?>",
                "inputRadioSelector": ".input-radio-amount-<?php echo $block->getIdentifier(); ?>",
                "setAjaxRefreshOnSuccessMsg": "<?php echo __('The page will be refreshed.') ?>"
            }
        }
    }
    </script>


