<?php /* @var $block Fidesio\Donation\Block\Donation\DonationBlock */  ?>

    <section class="fidesio-donation">


        <form method="POST" action=" <?php echo $block->getAddDonationUrl(); ?>" style="opacity: 3;" class="charity-form" id="fidesio-donation-product-addtocart-form-<?php echo $block->getIdentifier(); ?>">
            <?php echo $block->getBlockHtml('formkey'); ?>
        <header>
            <input type="checkbox" id="fidesio-donation-checkbox" name="scales">
            <label for="scales"><?php echo $block->getDetailDonationBlock()['title']; ?></label>
        </header>
        <div style="opacity:0.2; text-align: center; width: 100%; display: grid; grid-template-columns: 1fr 1fr 1fr; grid-gap: 10px 2em;" class="container fidesio-donation-block-wrapper">
        <div title="" style="" class="">
            <img src="<?php echo $block->getMediaUrl(); ?>/fidesio/donation/<?php echo $block->getDetailDonationBlock()['image'];?>" alt="" class="" />
        </div>
        <div style=" " >
            <select id="fidesio-donation-amount-select" name="donation_amount" >
                <option>Choisir un montant</option>
                <?php foreach ($block->getFixedAmounts() as $amount=> $key):; ?>
                <option value="<?php echo $amount; ?>"><?php echo $block->getCurrencySymbol().' '.$amount; ?></option>
                <?php endforeach;?>
            </select>

        </div>
        <div style="" >
            <?php echo $block->getDetailDonationBlock()['description']; ?>
        </div>
        </div>

        </form>
    </section>



    <script type="text/x-magento-init">
    {
        "*": {
            "donation":
            {
                "ContainerDonation":".fidesio-donation-block-wrapper",
                "identifier": "<?php echo $block->getIdentifier(); ?>",
                 "CheckboxSelector":"#fidesio-donation-checkbox",
                 "SelectAmount":"#fidesio-donation-amount-select",
                 "addDonationFormId": "#fidesio-donation-product-addtocart-form-<?php echo $block->getIdentifier(); ?>",
                "inputRadioSelector": ".input-radio-amount-<?php echo $block->getIdentifier(); ?>",
                "setAjaxRefreshOnSuccessMsg": "<?php echo __('The page will be refreshed.') ?>"
            }
        }
    }
    </script>


